import Head from 'next/head'
import 'tailwindcss/tailwind.css'

import Header from './header';




export default function Home() {


  return (
    <div>
      <Head>
        <title>OpenReallife</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" /> 
      <main className='flex items-center flex-wrap bg-black h-screen text-white pl-52 pr-52'>
        <div className='h-32 w-3/4 justify-center'>
          <div className='left h-32 bg-or-blue'></div>
          <div className='right h-32 bg-or-green'></div>
        </div>
      </main>
    </div>
  )
}
