import Head from 'next/head'
import styles from '../../styles/Home.module.css'



export default function Profile({id}) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Profile | OpenReallife</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          PROFILE {id}
        </h1>
      </main>
    </div>
  )
}
